In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
import pylab as pl

In [2]:
from sklearn import datasets
img = datasets.load_digits()

In [3]:
print(img.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [4]:
print(img.images[0])

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


In [5]:
x = img.data/img.data.max()
x[0]

array([0.    , 0.    , 0.3125, 0.8125, 0.5625, 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.8125, 0.9375, 0.625 , 0.9375, 0.3125, 0.    ,
       0.    , 0.1875, 0.9375, 0.125 , 0.    , 0.6875, 0.5   , 0.    ,
       0.    , 0.25  , 0.75  , 0.    , 0.    , 0.5   , 0.5   , 0.    ,
       0.    , 0.3125, 0.5   , 0.    , 0.    , 0.5625, 0.5   , 0.    ,
       0.    , 0.25  , 0.6875, 0.    , 0.0625, 0.75  , 0.4375, 0.    ,
       0.    , 0.125 , 0.875 , 0.3125, 0.625 , 0.75  , 0.    , 0.    ,
       0.    , 0.    , 0.375 , 0.8125, 0.625 , 0.    , 0.    , 0.    ])

In [6]:
y = img.target
y

array([0, 1, 2, ..., 8, 9, 8])

In [7]:
n_samples = len(x)

In [8]:
x_train = x[:int(0.8*n_samples)]
x_train.shape

(1437, 64)

In [9]:
y_train = y[: int(0.8*n_samples)]
y_train.shape

(1437,)

In [10]:
x_test = x[int(0.8*n_samples):]
x_test.shape

(360, 64)

In [11]:
y_test = y[int(0.8*n_samples):]
y_test.shape

(360,)

In [40]:
from sklearn.linear_model import LogisticRegression
regr = LogisticRegression(solver = 'lbfgs', C = 0.01, max_iter = 1000, multi_class = 'multinomial')
regr.fit(x_train, y_train)

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [41]:
y_test[0:20]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4])

In [42]:
yhat = regr.predict(x_test)
yhat[0:20]

array([2, 3, 4, 9, 6, 7, 9, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4])

In [43]:
yhat_proba = regr.predict_proba(x_test)
yhat_proba

array([[0.019034  , 0.07680319, 0.53749795, ..., 0.02182437, 0.06979853,
        0.03510195],
       [0.03856049, 0.06773958, 0.11114866, ..., 0.04611616, 0.07646807,
        0.12207268],
       [0.05350984, 0.07064866, 0.02868567, ..., 0.09484773, 0.05032178,
        0.02890423],
       ...,
       [0.04635625, 0.18704119, 0.07967227, ..., 0.047451  , 0.28691401,
        0.04935036],
       [0.13078559, 0.06652682, 0.04345924, ..., 0.05348233, 0.11406892,
        0.29372696],
       [0.06787285, 0.08532862, 0.08810472, ..., 0.03637823, 0.22843996,
        0.10975734]])

In [44]:
a_1 = regr.score(x_train, y_train)
a_1

0.9283228949199722

In [45]:
a_2 = regr.score(x_test, y_test)
a_2

0.8611111111111112

In [46]:
a_3 = regr.score(x_test, yhat)
a_3

1.0

In [56]:
from sklearn.metrics import jaccard_similarity_score, accuracy_score
a_4 = jaccard_similarity_score(y_test, yhat)
a_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.8611111111111112

In [57]:
a_5 = accuracy_score(y_test, yhat)
a_5

0.8611111111111112

In [47]:
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier(n_neighbors = 1)
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [48]:
y_test[0:20]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4])

In [49]:
y_pred = knn.predict(x_test)
y_pred[0:20]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4])

In [50]:
b_1 = knn.score(x_train, y_train)
b_1

1.0

In [51]:
b_2 = knn.score(x_test, y_test)
b_2

0.9555555555555556

In [52]:
b_3 = knn.score(x_test, y_pred)
b_3

1.0

In [58]:
b_4 = jaccard_similarity_score(y_test, y_pred)
b_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.9555555555555556

In [59]:
b_5 = accuracy_score(y_test, y_pred)
b_5

0.9555555555555556

In [60]:
from sklearn import svm
clf = svm.SVC(kernel = 'poly', gamma = 'auto')
clf.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [61]:
y_test[0:30]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4, 1, 7,
       7, 3, 5, 1, 0, 0, 2, 2])

In [62]:
yhat_1 = clf.predict(x_test)
yhat_1[0:30]

array([2, 3, 4, 3, 6, 7, 3, 3, 0, 3, 3, 3, 6, 3, 0, 3, 3, 3, 3, 4, 1, 7,
       7, 3, 3, 3, 0, 0, 3, 3])

In [63]:
c_1 = clf.score(x_train, y_train)
c_1

0.6443980514961726

In [64]:
c_2 = clf.score(x_test, y_test)
c_2

0.6166666666666667

In [65]:
c_3 = clf.score(x_test, yhat_1)
c_3

1.0

In [66]:
c_4 = jaccard_similarity_score(y_test, yhat_1)
c_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.6166666666666667

In [67]:
c_5 = accuracy_score(y_test, yhat_1)
c_5

0.6166666666666667

In [68]:
from sklearn import tree
clf_1 = tree.DecisionTreeClassifier()
clf_1.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [69]:
y_test[0:40]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4, 1, 7,
       7, 3, 5, 1, 0, 0, 2, 2, 7, 8, 2, 0, 1, 2, 6, 3, 3, 7])

In [70]:
ypred_1 = clf_1.predict(x_test)
ypred_1[0:40]

array([2, 3, 4, 3, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4, 9, 7,
       4, 3, 5, 9, 0, 0, 2, 2, 7, 3, 2, 0, 3, 2, 6, 3, 3, 7])

In [71]:
d_1 = clf_1.score(x_train, y_train)
d_1

1.0

In [72]:
d_2 = clf_1.score(x_test, y_test)
d_2

0.7916666666666666

In [73]:
d_3 = clf_1.score(x_test, ypred_1)
d_3

1.0

In [74]:
d_4 = jaccard_similarity_score(y_test, ypred_1)
d_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.7916666666666666

In [75]:
d_5 = accuracy_score(y_test, ypred_1)
d_5

0.7916666666666666

In [76]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000)
rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [77]:
y_test[0:15]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0])

In [78]:
yhat_2 = rf.predict(x_test)
yhat_2[0:15]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0])

In [113]:
e_1 = rf.score(x_train, y_train)
e_1

1.0

In [114]:
e_2 = rf.score(x_test, y_test)
e_2

0.925

In [115]:
e_3 = rf.score(x_test, yhat_2)
e_3

1.0

In [116]:
e_4 = jaccard_similarity_score(y_test, yhat_2)
e_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.925

In [117]:
e_5 = accuracy_score(y_test, yhat_2)
e_5

0.925

In [85]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
gsn = GaussianNB()
gsn.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [86]:
y_test[0:10]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9])

In [88]:
ypred_2 = gsn.predict(x_test)
ypred_2[0:10]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9])

In [118]:
f_1 = gsn.score(x_train, y_train)
f_1

0.8803061934585943

In [119]:
f_2 = gsn.score(x_test, y_test)
f_2

0.8138888888888889

In [120]:
f_3 = gsn.score(x_test, ypred_2)
f_3

1.0

In [121]:
f_4 = jaccard_similarity_score(y_test, ypred_2)
f_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.8138888888888889

In [122]:
f_5 = accuracy_score(y_test, ypred_2)
f_5

0.8138888888888889

In [94]:
mul = MultinomialNB()
mul.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [95]:
y_test[0:15]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0])

In [97]:
yhat_3 = mul.predict(x_test)
yhat_3[0:15]

array([2, 3, 4, 9, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0])

In [99]:
g_1 = mul.score(x_train, y_train)
g_1

0.9171885873347251

In [100]:
g_2 = mul.score(x_test, y_test)
g_2

0.8388888888888889

In [101]:
g_3 = mul.score(x_test, yhat_3)
g_3

1.0

In [102]:
g_4 = jaccard_similarity_score(y_test, yhat_3)
g_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.8388888888888889

In [103]:
g_5 = accuracy_score(y_test, yhat_3)
g_5

0.8388888888888889

In [104]:
ber = BernoulliNB()
ber.fit(x_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [106]:
y_test[0:15]

array([2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0])

In [105]:
ypred_3 = ber.predict(x_test)
ypred_3[0:15]

array([2, 3, 4, 5, 6, 7, 9, 9, 0, 9, 5, 5, 6, 5, 0])

In [107]:
h_1 = ber.score(x_train, y_train)
h_1

0.8768267223382046

In [108]:
h_2 = ber.score(x_test, y_test)
h_2

0.7972222222222223

In [109]:
h_3 = ber.score(x_test, ypred_3)
h_3

1.0

In [110]:
h_4 = jaccard_similarity_score(y_test, ypred_3)
h_4

c:\users\raghavendra\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.7972222222222223

In [111]:
h_5 = accuracy_score(y_test, ypred_3)
h_5

0.7972222222222223

In [123]:
df = pd.DataFrame({'Training Score' : [a_1, b_1, c_1, d_1, e_1, f_1, g_1, h_1],
                  'Testing Score' : [a_2, b_2, c_2, d_2, e_2, f_2, g_2, h_2],
                  'Predicted Score' : [a_3, b_3, c_3, d_3, e_3, f_3, g_3, h_3],
                  'Jaccard_Similarity_Score' : [a_4, b_4, c_4, d_4, e_4, f_4, g_4, h_4],
                  'Accuracy Score' : [a_5, b_5, c_5, d_5, e_5, f_5, g_5, h_5]}, index = ['Logistic', 'KNN', 'SVC', 'Decision Tree', 'Random Forest', 'GaussianNB', 'MultinomialNB', 'BernoulliNB'])
df

Training Score  Testing Score  Predicted Score  \
Logistic             0.928323       0.861111              1.0   
KNN                  1.000000       0.955556              1.0   
SVC                  0.644398       0.616667              1.0   
Decision Tree        1.000000       0.925000              1.0   
Random Forest        1.000000       0.925000              1.0   
GaussianNB           0.880306       0.813889              1.0   
MultinomialNB        0.917189       0.838889              1.0   
BernoulliNB          0.876827       0.797222              1.0   

               Jaccard_Similarity_Score  Accuracy Score  
Logistic                       0.861111        0.861111  
KNN                            0.955556        0.955556  
SVC                            0.616667        0.616667  
Decision Tree                  0.925000        0.925000  
Random Forest                  0.925000        0.925000  
GaussianNB                     0.813889        0.813889  
MultinomialNB                  0.838889        0.838889  
BernoulliNB                    0.797222        0.797222